### PR TITLE
#66 - updated general settings

### LINKED ISSUE #66: Additional general settings
Things below should be configurable from the dashboard:
- [ ] university logo
- [ ] primary and secondary color for theming

### PR DESCRIPTION
**Pull request by kamilpiech97**
Should close #66.
Added option to manage primary, secondary color and logo file.
Added tests.

### CODE REVIEW

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. When I upload logo ~15 MB size, I see error

image

2. Please fix GitHub check annotations

image

3. I changed primary and secondary colors and logo - I don't see that anywhere the colors is changed nor logo. 

4. Can we change style of color input? Now it looks like this

image

Something like this will look much better

image

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. I set some image as a logo in "Ustawienia" -> I go to another page like "Studenci" -> I go one more time to "Ustawienia" -> I change primary color -> I click "Zapisz" button -> I see error "Pole logo musi być obrazkiem."

**Comment by kamilpiech97** [comment]
> 1. I set some image as a logo in "Ustawienia" -> I go to another page like "Studenci" -> I go one more time to "Ustawienia" -> I change primary color -> I click "Zapisz" button -> I see error "Pole logo musi być obrazkiem."

fixed

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. I still have error when I upload file like ~15MB
2. I still have problem with that

I set some image as a logo in "Ustawienia" -> I go to another page like "Studenci" -> I go one more time to "Ustawienia" -> I change primary color -> I click "Zapisz" button -> I see error "Pole logo musi być obrazkiem."

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Pull request merged**
