### PR TITLE
#24 - news

### PR DESCRIPTION
**Pull request by krzysztofrewak**
This partially solves #24.

obraz

obraz

### CODE REVIEW

**Review by kamilpiech97 — DISMISSED** [review]

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. In validation message, the word "content" is not translated

`Pole content jest wymagane.`

2. Date of publication is shown in UTC, but I think we should show in our timezone. Also styling of text doesn't work

image

3. When I click on the news to go to details, I see some random text

image

4. When no news are published, we should make some nice empty state or at least hide pagination and add text like "Brak aktualności"

image

**Comment by kamilpiech97** [comment]
@krzysztofrewak conflicts

**Review by EwelinaSkrzypacz — COMMENTED** [review]
Please fix GitHub warnings

image

**Comment by krzysztofrewak** [comment]
@EwelinaSkrzypacz, all done.

image

**Review by EwelinaSkrzypacz — COMMENTED** [review]
How about this warning?

image

**Comment by krzysztofrewak** [comment]
@EwelinaSkrzypacz, we cannot do anything, as we are sending formatted data from backend.

**Review by EwelinaSkrzypacz — DISMISSED** [review]

**Comment by krzysztofrewak** [comment]
@EwelinaSkrzypacz, I added `sanitizeHtml()` for contents.

**Review by kamilpiech97 — APPROVED** [review]

**Review by kamilpiech97 — APPROVED** [review]

**Pull request merged**
