### PR TITLE
#29 - grades page

### LINKED ISSUE #29: Grades page
Grades page should:
- [ ] be available under `\oceny` page
- [ ] provide a form where student should choose semester of interest, course from courses attached to the selected semester, group from groups attached to the selected course and his index number
- [ ] for existing student a matrix with all grades should be shown
- [ ] all other students names should be truncated and unidentifiable (GDPR) and maybe randomized
- [ ] selected items in the form should be added to URL
- [ ] nice to have: next to the index number input there could be "Remember me (in cache)" checkbox

This is related to #11 and #12  and should be done after implementation of these tasks.

### PR DESCRIPTION
**Pull request by kamilpiech97**
This should close #29.

A page called `oceny` has been added, where the student can see his or her grade table after selecting the semester, course, group and entering the index number. Added some tests.

**Preview:**
screencapture-keating-blumilk-localhost-oceny-01hfhdrdjwnwt9pyd1r2zn8w9y-01hfhdrdkdx87djrg5pvzwt0vb-01hfhdrfa1t5wvdetm5g7y309t-2275-2023-11-20-08_37_35

**Mobile view:**
screencapture-keating-blumilk-localhost-oceny-01hfhdrdjwnwt9pyd1r2zn8w9y-01hfhdrdkdx87djrg5pvzwt0vb-01hfhdrfa1t5wvdetm5g7y309t-2275-2023-11-20-08_38_17

### CODE REVIEW

**Review by EwelinaSkrzypacz — COMMENTED** [review]
When I add a column as a teacher it's blank:

image

But on "Oceny" page, when I enter some index number, the column is red

image

Should be like this?

**Comment by kamilpiech97** [comment]
> When I add a column as a teacher it's blank:
> 
> image
> 
> But on "Oceny" page, when I enter some index number, the column is red
> 
> image
> 
> Should be like this?

fixed

**Review by krzysztofrewak — CHANGES_REQUESTED** [review]
I would change behaviour of clicking: [empty state] -> [green] -> [red] -> [empty] -> (...)

Now it's [empty] -> [red] -> [green] -> [red] -> (...), so you cannot go back to empty. Green is also more often used than red, so it should go first.

**Comment by krzysztofrewak** [comment]
Hmm... Looks like first click can be single click and then you're getting green. Next one needs to be red? It's weird.

**Review by krzysztofrewak — CHANGES_REQUESTED** [review]
Also there should be names of students as well (in dashboard panel):

image

**Comment by EwelinaSkrzypacz** [comment]
Conflicts :(

**Comment by kamilpiech97** [comment]
> Hmm... Looks like first click can be single click and then you're getting green. Next one needs to be red? It's weird.

Changed into:
1. first click going to green
2. doubleclick going to red
3. and next doubleclick going like this: white => green => red => white....

For double-clicking? For example, if we want to add a rating to a cell, we have to click it and if we had an action that changed the color to one click, changing the rating would involve changing the color, which could be annoying.

**Comment by kamilpiech97** [comment]
> Also there should be names of students as well (in dashboard panel):
> 
> image

Lets check doubleclick :D

**Comment by EwelinaSkrzypacz** [comment]
Or maybe display students names and in parenthesis index number?

Like: Jan Kowalski (123123) and bold name or something?

**Comment by kamilpiech97** [comment]
> Or maybe display students names and in parenthesis index number?
> 
> Like: Jan Kowalski (123123) and bold name or something?

Fixed

**Review by EwelinaSkrzypacz — DISMISSED** [review]

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Review by krzysztofrewak — APPROVED** [review]

**Pull request merged**
